name: setup-environment
description: Composite action to setup environment and install dependencies

runs:
  using: composite
  steps:
    - name: 🤹‍♂️ Install asdf
      uses: asdf-vm/actions/setup@v3

    - name: 🗂️ Cache asdf
      id: cache-asdf
      uses: actions/cache@v4
      env:
        cache-name: cache-asdf
        cache-path: ~/.asdf
      with:
        path: ${{ env.cache-path }}
        key: ${{ runner.os }}-se-${{ env.cache-name }}-${{ hashFiles('**/.tool-versions') }}
        restore-keys: |
          ${{ runner.os }}-se-${{ env.cache-name }}-

    - name: 🛠️ Install tools from .tool-versions
      if: ${{ steps.cache-asdf.outputs.cache-hit != 'true' }}
      continue-on-error: true
      uses: asdf-vm/actions/install@v3

    - name: 🗂️ Cache .venv
      id: cache-venv
      uses: actions/cache@v4
      env:
        cache-name: cache-venv
        cache-path: .venv
      with:
        path: ${{ env.cache-path }}
        key:
          ${{ runner.os }}-se-${{ env.cache-name }}-${{ hashFiles('**/.tool-versions') }}-${{
          hashFiles('**/poetry.lock') }}

    - name: 📥 Install dependencies
      if: ${{ steps.cache-venv.outputs.cache-hit != 'true' }}
      shell: bash
      run: make install
